---
- name: discover current link
  stat:
    path: /opt/openstack/current
  register: current

- name: discover packages
  command: ls
  args:
    chdir: /opt/openstack/current
  register: pkgs
  when: current.stat.isdir|default(False)

- name: remove current link
  file:
    path: /opt/openstack/current
    state: absent
  when: current.stat.isdir|default(False)

- name: make current dir
  file:
    path: /opt/openstack/current
    state: directory
  when: current.stat.isdir|default(False)
